### ISSUE TITLE
Set application ID for linux build

### ISSUE THREAD

**Issue by needlesslygrim** [SCIEDEV/PastPaperMaster#4]
The application ID is currently set to `com.example.past_paper_master`, at least on Linux. It should probably be set to something like `dev.scie.PastPaperMaster`, or `com.github.micfong_z.PastPaperMaster`, as explained [here](https://wiki.gnome.org/HowDoI/ChooseApplicationID).

**Comment by needlesslygrim** [comment]
[This](https://github.com/SCIEDEV/PastPaperMaster/blob/b7a0df99c866e3a9c2e0e9f4daca9a7bd5b81959/linux/CMakeLists.txt#L10C1-L10C52) is where it's set, but I'm not sure what you want it set to...

**Comment by micfong-z** [comment]
I prefer to go with `dev.scie.PastPaperMaster` since this repo is under SCIEDEV account. You can open a PR for this if you wish, or I'll do it sometime later after the exam series.

**Comment by needlesslygrim** [comment]
Ok, opened #8 :^)
